const API_URL = process.env.NEXT_PUBLIC_API_URL;
const ENVIRONMENT = process.env.NEXT_PUBLIC_ENVIRONMENT;
const SENTRY_URL = process.env.NEXT_PUBLIC_SENTRY_URL;

export { API_URL, SENTRY_URL, ENVIRONMENT };
