import rawQuizzData from '~/shared/quizz-2027.json';
import { normalizeWord } from './diacritics';
import type { QuizzTheme, QuizzQuestion } from '@app/types/quizz';

/**
 * "Et si un(e) autre gagnait...": one question per candidate still in the race, asking how the
 * user would feel if that person won. Generated by `npm run generate-gagnait-theme`, never edited
 * by hand, and kept out of candidate-to-candidate proximity since its candidate answers derive
 * from it.
 */
export const gagnaitThemeId = 'theme-et-si-un-autre-gagnait-2027';

// A theme without any question is a placeholder in the JSON (the "gagnait" theme shipped empty
// for months). It must never be listed nor counted, otherwise the theme count disagrees from one
// page to the next.
const rawQuizz: QuizzTheme[] = (rawQuizzData as QuizzTheme[]).filter((theme) => theme.questions.length > 0);

const formatQuizzForSearch = (quizzData: QuizzTheme[]) =>
  quizzData.map((theme) => {
    const questions = theme.questions.map((q) => q.fr).join(' ');
    const answers = theme.questions.map((q) => q.answers.join(' ')).join(' ');
    return normalizeWord(`${theme.fr} ${questions} ${answers}`.toLocaleLowerCase());
  });

const formatAnswers = (answers: string[]) =>
  answers.map((answer, answerIndex) => `      ${answerIndex + 1}. ${answer}`).join('\n');
const formatQuestions = (themeIndex: number, questions: QuizzQuestion[]) =>
  questions
    .map(
      (question, questionIndex) =>
        `  ${'ABCDEFGHIJKLMNOPQRSTUVWXYZ'[themeIndex]}${questionIndex + 1} - ${question.fr}\n${formatAnswers(question.answers)}`,
    )
    .join('\n\n');

const formatQuizzText = (quizzData: QuizzTheme[]) =>
  quizzData
    .map(
      (theme, index) =>
        `${'ABCDEFGHIJKLMNOPQRSTUVWXYZ'[index]} - ${theme.fr}\n\n  ${formatQuestions(index, theme.questions)}`,
    )
    .join('\n\n\n');

const colors = [
  '#e6194B',
  '#3cb44b',
  '#ffe119',
  '#4363d8',
  '#f58231',
  '#911eb4',
  '#42d4f4',
  '#f032e6',
  '#bfef45',
  '#fabed4',
  '#469990',
  '#dcbeff',
  '#9A6324',
  '#fffac8',
  '#800000',
  '#aaffc3',
  '#808000',
  '#ffd8b1',
  '#000075',
  '#a9a9a9',
  '#ffffff',
  '#000000',
];

const enrichedQuizz: QuizzTheme[] = rawQuizz.map((theme, index) => ({
  ...theme,
  backgroundColor: colors[index],
}));

const quizzForSearch = formatQuizzForSearch(enrichedQuizz);
const quizzDownload = formatQuizzText(rawQuizz);
const quizzQuestions: QuizzQuestion[] = rawQuizz.reduce<QuizzQuestion[]>((questions, theme) => {
  return [...questions, ...theme.questions];
}, []);
const quizzQuestionsCount = quizzQuestions.length;
const quizzThemesCount = rawQuizz.length;

export { enrichedQuizz as quizz, quizzForSearch, quizzDownload, quizzQuestions, quizzQuestionsCount, quizzThemesCount };
